version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    env_file:
      - .env
    environment:
      - ENV=production
